name: doclense
description: An Indian made Open source PDF creator Android app
publish_to: "none"

version: 1.0.1+2

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_splash_screen: ^1.3.0
  camera: ^0.11.1
  cupertino_icons: ^1.0.8
  double_back_to_close_app: ^2.1.0
  easy_folder_picker: ^1.3.4
  flutter_launcher_icons: ^0.14.4
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.2.0
  fluttertoast: ^8.2.12
  image_gallery_saver: ^2.0.3  # Substituto moderno para gallery_saver
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_cropper: ^9.1.0
  image_picker: ^1.1.2
  intl: 0.19.0  # Versão compatível com wiredash
  introduction_screen: ^3.1.17
  open_file: ^3.5.10
  package_info_plus: ^8.3.0
  path: ^1.9.1
  path_provider: ^2.1.5
  pdf: ^3.11.3
  permission_handler: ^12.0.0+1
  image_editor_plus: ^1.0.6  # Substituto moderno para photofilters
  printing: ^5.14.2
  provider: ^6.1.5
  quick_actions: ^1.1.0
  rating_dialog: ^2.0.4
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  source_span: ^1.10.1
  url_launcher: ^6.3.1
  wiredash: ^2.5.0

dev_dependencies:
  build_runner: ^2.5.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  lint: ^2.8.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/
    - assets/aboutPage/
    - assets/images/team/
